# Введение {.unnumbered}

## Об этом курсе
Этот сайт содержит материалы к курсу “Программирование на R для филологов” для магистерской программы НИУ ВШЭ “Русская литература и компаративистика”.


## Программа

Курс 2025/2026 г. читается два модуля и включает в себя 8 основных тем.

**Модуль 1. Основы работы в R**

(@) Начало работы. Контроль версий.
(@) Табличные данные. Анализ датасета.
(@) Распознавание изображений.
(@) Нормализация. Регулярные выражения.

**Модуль 2. Редакторские инструменты**

(@) Основы работы с TEI XML.
(@) Добавление разметки с использованием LLM.
(@) Публикационная система Quarto.
(@) Консолидирующий проект.


## Расписание

Занятия в первом модуле: 6 и 13 сентября, 4 и 18 октября Занятия во втором модуле: 1, 15 и 29 ноября, 13 декабря.

## Оценивание

Две домашние, одна лабораторная и проект в каждом модуле.

## Благодарности

В разработке этого курса мне помогало множество людей: Дарья Глебова, Александра Горшенина, Георгий Мороз, Борис Орехов, Софья Порфирьева, Анастасия Орлова, Екатерина Гуреева, Анастасия Богданова и многие другие. Все недостатки остаются на моей совести.

## Обратная связь

Этот курс находится в разработке. Если вы заметили ошибку или опечатку, можно сообщить по почте oalieva@hse.ru или оставить issue в [репозитории](https://github.com/locusclassicus/philology_2025/tree/main) курса на GitHub.
